### ISSUE TITLE
Topology template's yaml view on Linux is not well displayed

### ISSUE THREAD

**Issue by eyal33** [alien4cloud/alien4cloud#54]
Hi,
Â is displayed instead of space in the Topology template's yaml view.
I ran it on Linux Red Hat Enterprise Linux Server release 5.6 (Tikanga).
Browsers: Firefox & chrome.
on IE the yaml is empty.

Thanks a lot,
Eyal

![topologyviewyaml](https://cloud.githubusercontent.com/assets/5900936/5992087/1d722612-aa20-11e4-9f5c-492ef6983cb4.png)

**Comment by PierreLemordant** [comment]
Hi,

Which version of Alien do you use ?

Regards,

Pierre

**Comment by lucboutier** [comment]
Hi Eyal,

In addition to Pierre question I would like to know if you start alien 4 cloud using the standalone deployment (recommended) or using the war file deployed in a container (we will deprecate this usage in future) ?
The issue is actually related to the server encoding and should not exists if you deploy in standalone mode.

That said the yaml feature is not complete yet as the yaml is not TOSCA compliant currently. This is part of the roadmap of our next coming sprints.

HTH,

Luc

**Comment by eyal33** [comment]
Hi Pierre & Luc,

I am using version 1.0.0-SM19.
I took the standalone version and run it on jetty server. 
I'll check the container war and will update.

Btw, is there a reason to deprecate the container war ?

Regards,
Eyal

**Comment by lucboutier** [comment]
Hi Eyal,

I'm a bit confused on how you are running the standalone version. Do you just run it using the 'java -jar alien4cloud-ui-VERSION-standalone.war' command ?
See: http://alien4cloud.github.io/#/documentation/getting_started/getting_started.html

Regarding deprecation the question is more is there any reason why not to deprecate it ? Basically some things are a bit different in the code between both versions  and as we don't see any use case why to keep both I think it is better to keep just one version that all users will run in the same way.

Luc

**Comment by eyal33** [comment]
Hi Luc,
I unzipped a jetty server on my linux machine.
Then, I put the standalone war(since I later know you have a container jar) under the webapp directory and start the jetty server. (After starting the server I needed to create a directory called /root/.alien/upload under the working directory of jetty, so I created a soft link after the server was up(a workaround)).

In our project we want to deploy more than one application on the same server(It can save monitoring, memory...). I'll be happy to know what are the differences in the code between the container and standalone versions.

**Comment by lucboutier** [comment]
Hi Eyal,

Can you please tell us from which company you are from and some more informations on your project context, if you like to do that in private you can e-mail at "luc at fastconnect .fr"

To come back on the code side the effort is not much on the code by itself but more on the impacts and testing that is implied by multiple deployment options. As you can see for example this yaml issue is specific to the war deployment - and actually because I guess that spring boot (standalone launcher) is registering automatically an UTF-8 filter for js scripts.
